version: '3.9'

services:
  contract-api:
    container_name: contract-api
    build: .
    restart: always
    ports:
      - '3030:3000'
    shm_size: '1gb'
    environment:
      - NODE_ENV=production
      - PLAYWRIGHT_PRELAUNCH=true
      - PLAYWRIGHT_WARMUP=true

